Setting up services User and Channel
DoomDuck/transcendence pull request #46
Opened 2022-07-12 12:12 UTC by Hgallien

- [ ] user permanent information in database
- [ ] user non permanent information structrured
- [ ] channel structure in setup
- [ ] channel sockets
- [ ] private message sockets

2022-07-19 10:37 UTC, DoomDuck requested changes
You don't follow the convention the naming convention:
> There is PR on this #54 that needs review

Channel related code should not be in this PR (please move it to another PR)
There is an inconsistency with plurals (I would personally go without plural there)
You have `databaseFiles.controller.ts` and `databaseFile.entity.ts`
It is also hard to follow with implicit return types I think it would be nice to [block this in the tsconfig](https://www.typescriptlang.org/tsconfig#noImplicitReturns)

2022-07-20 06:53 UTC, DoomDuck requested changes
missing the new `nest-cli.json`
And previous concerns have not been addressed

2022-07-20 06:53 UTC, DoomDuck commented on tsconfig.json
> +{
This shouldn't be here :eyes:

2022-07-20 10:27 UTC, Hgallien commented on src/back/user/databaseFiles.controller.ts
> +}
UseInterceptors is useless here, the decorator is use on the class but the one fonction in it doesn't use it. I've removed it and it work

2022-07-20 12:19 UTC, DoomDuck requested changes
Game parts should likely not be part of this PR

Almost there :slightly_smiling_face:

2022-07-20 12:19 UTC, DoomDuck commented on package.json
> +		"class-transformer": "^0.5.1",
Shouldn't we remove this if it is not needed

2022-07-20 12:19 UTC, DoomDuck commented on src/back/user/game.entity.ts
> +export class Gane {
I think this is a typo

2022-07-20 12:19 UTC, DoomDuck commented on src/back/user/game.entity.ts
> +  playerTwoScore: Id;
Those should be `number` not `Id`

2022-07-20 12:19 UTC, DoomDuck commented on src/back/user/game.entity.ts
> +  playerTwo: string;
Those should likely be `Id`s

2022-07-20 12:19 UTC, DoomDuck commented on src/back/user/requestWithUser.interface.ts
> +export default RequestWithUser;
This doesn't seem to useful maybe it shouldn't be in the PR

2022-07-20 12:41 UTC, DoomDuck submitted a review, later dismissed
Welldone :+1:

2022-07-20 13:09 UTC, DoomDuck approved these changes

2022-07-20 13:15 UTC, merged