Refacto front
DoomDuck/transcendence pull request #53
Opened 2022-07-16 21:51 UTC by emmaafrn

Holà this is my code with the good things and the less good things (like my modals windows...)

2022-07-17 09:11 UTC, DoomDuck reviewed
Modal doesn't have a clear way of interacting with others.
It emits an event and also exposes isOpenModal

2022-07-18 14:40 UTC, emmaafrn commented on src/front/Friend.svelte
> +  }
NOOOO you suck !
```svelte
<Modal {isOpenModal} {friendName} {image} on:closeModal={() => isOpenModal = false} />
```
Should be used instead

2022-07-19 11:43 UTC, DoomDuck requested changes
You have a warning when you compile the project

2022-07-19 13:26 UTC, DoomDuck requested changes
Your alt= attributes are quite strange, those are the fields read for accessibility reasons

2022-07-19 15:06 UTC, emmaafrn commented on src/front/Profile.svelte
> +  }
<h1> changed to <h3> but I don't understand why my alt attribute is strange,
I thing it's a pretty good description of what my <img> element is.

  <div id="Profile">
    
    <img class="roundedImageProfile" src={image} alt="profilepic" />
    <h3>{friendName}</h3>
    <p> iD: {iD}</p>
  
  </div>

2022-07-20 06:40 UTC, DoomDuck approved these changes
It's a lot better now I like it :grin:

2022-07-20 14:54 UTC, DoomDuck approved these changes

2022-07-20 14:54 UTC, merged